# Simple data transformation workflow
name: OECD Unemployment Rate CHE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch

jobs:
  oecd:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v3
      - run: git version
      - run: rm -rf README.md
      - run: |
          Rscript -e 'install.packages(c("kofdata","tsbox"))'
          chmod +x
          ./demo_gha.R
      - run: ls -lah
